name = "pitchpubs"
main = "dist/index.js"
compatibility_date = "2024-01-01"

workers_dev = true

routes = [
  { pattern = "pitchpubs.com/*", zone_name = "pitchpubs.com" },
  { pattern = "www.pitchpubs.com/*", zone_name = "pitchpubs.com" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pitchpubs-db"
database_id = "2bd2cc16-b106-46df-ab1d-d6397ab5b2f3"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "soccerbars-v2-images"
