name = "directory-template"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "directory-template-db"
database_id = "3516d0aa-73a1-4493-b483-a8e4e236b035"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "directory-template-images"
