name = "soccerbars-v2"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "soccerbars-v2-db"
database_id = "4dd686ac-3bc7-4e22-b878-65d79e46fc26"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "soccerbars-v2-images"
